### ISSUE TITLE
Monorepo Initialisation Task List

### ISSUE THREAD

**Issue by binaryben** [directus-labs/extensions#3]
- [x] ~~Migrate existing repos and preserve git history~~ #1 
- [ ] Update existing extensions
  - [ ] Update image location attributes -- #2 
  - [ ] Ensure consistent extension naming scheme
  - [ ] Ensure all packages build with PNPM
  - [ ] Add author and contributor attributes to package.json
  - [ ] Update extension versions with patch release and publish
  - [ ] Delete old repos
- [ ] Add community health files #5
  - [x] Readme
  - [x] Contributing
  - [ ] Security
  - [x] Issue templates
- [ ] Setup minimum viable workflow
  - [ ] Add PR template
  - [x] Set repo to require PR to commit to main
  - [x] Make repo public to enable protection settings
  - [x] Implement a CLA signing process
  - [ ] Add code standards
